# workloads/services/vote/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app.kubernetes.io/name: vote
    app.kubernetes.io/component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: vote
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vote
    spec:
      containers:
      - name: vote-app
        image: vote-app-image:latest  
        command: ["sh", "-c", "echo 'Vote service placeholder running'; sleep infinity"]
        ports:
        - containerPort: 8080  
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: "10m"
            memory: "16Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"
        readinessProbe:
          exec:
            command: ["echo", "ready"]
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["echo", "alive"]
          initialDelaySeconds: 15
          periodSeconds: 20
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault