apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: base-chart
    releaseName: vote
    namespace: myvote-dev
    repo: file://../../../charts/base-chart
    valuesFile: ../../overlays/dev/values.yaml
