apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/girmaat/kubernetes-devsecops-cloud-platform
    targetRevision: HEAD
    path: workloads/services/vote/overlays/dev
    kustomize:
      images:
      - name: vote-app-image
        newName: k8s.gcr.io/pause
        newTag: "3.2"
  destination:
    server: https://kubernetes.default.svc
    namespace: vote-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true