apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/girmaat/kubernetes-devsecops-cloud-platform
    targetRevision: main
    path: workloads/services/vote/overlays/dev
    plugin: null
    kustomize:
      buildOptions: --enable-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: myvote-dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
